---
pagetitle: 'Climate crisis in charts'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse) ; library(showtext) ; library(ggtext) ; library(ggrepel) ; library(lubridate) ; library(scales)
```

```{r}
# Atmospheric CO2
# Source: NOAA
# URL: https://gml.noaa.gov/ccgg/trends/data.html

df <- read_csv("https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_mm_mlo.csv",
               skip = 40) %>% 
  filter(year >= 1960) %>% 
  mutate(date = as.Date(date_decimal(`decimal date`, tz = "UTC"))) %>% 
  select(date, average)

ggplot(df, aes(x = date, y = average, group = 1)) +
  geom_ribbon(aes(ymin = 280, ymax = average), fill = "#CBFFA9") +
  geom_line(linewidth = 1, colour = "#3EA303") +
  scale_x_date(expand = c(0.005, 0.005),
               breaks = seq.Date(as.Date("1960-01-01"), as.Date("2020-01-01"), by = "10 years"),
               date_labels = "%Y") + 
  scale_y_continuous(expand = c(0.005, 0.005), 
                     limits = c(280, 450)) +
  labs(x = NULL, y = NULL,
       title = "<span>Atmospheric CO<sub>2</sub>",
       subtitle = "Monthly average, Mauna Loa Observatory",
       tag = "Chart baseline is 280ppm - the preindustrial average",
       caption = "Source: NOAA") +
  theme_minimal(base_size = 12) +
  theme(plot.margin = unit(rep(1.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(colour = "#000000"),
        plot.title.position = "plot",
        plot.title = element_markdown(face = "bold", size = 18),
        plot.subtitle = element_text(margin = margin(b = 25)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10), size = 12),
        plot.tag = element_text(size = 10),
        plot.tag.position = c(0.2, 0.01)) +
  annotate("text", x = as.Date("1964-01-01"), y = 445, label = "Parts per million", size = 3) +
  geom_text(data = filter(df, date == last(date)),
            aes(label = paste0(format(date, "%b %Y"), "\n", round(average, 1), "ppm")),
            hjust = -0.1, size = 3, fontface = "bold") +
  coord_cartesian(clip = "off")
```

```{r}
# Annual CO2 emissions
# Source: Our World in Data
# URL: https://ourworldindata.org/co2-emissions

df <- read_csv("data/annual-co2-emissions-per-country.csv") %>% 
  filter(Entity == "World", Year >= 1850) %>% 
  select(Year, Value = `Annual CO₂ emissions`) %>% 
  mutate(Year = ymd(Year, truncated = 2L),
         Value = Value/1000000000) # Billion tonnes CO2

ggplot(df, aes(x = Year, y = Value, group = 1)) +
  geom_area(fill = "#CBFFA9") +
  geom_line(linewidth = 1, colour = "#3EA303") +
  scale_x_date(expand = c(0.005, 0.005),
               breaks = seq.Date(as.Date("1850-01-01"), as.Date("2022-01-01"), by = "50 years"),
               date_labels = "%Y") + 
  scale_y_continuous(expand = c(0.005, 0.005), 
                     limits = c(0, 43)) +
  labs(x = NULL, y = NULL,
       title = "CO<sub>2</sub> emissions from fossil fuel burning",
       subtitle = "Annual global CO<sub>2</sub> emissions from fossil fuels and industry",
       caption = "Source: Our World in Data") +
  theme_minimal(base_size = 12) +
  theme(plot.margin = unit(rep(1.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(colour = "#000000"),
        plot.title.position = "plot",
        plot.title = element_markdown(face = "bold", size = 18),
        plot.subtitle = element_markdown(margin = margin(b = 25)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10), size = 12)) + 
  annotate("text", x = as.Date("1860-01-01"), y = 42, label = "Billion tonnes", size = 3) +
  geom_point(data = filter(df, Year == last(Year)),
             aes(x = Year, y = Value), 
             fill = "#CBFFA9", colour = "#3EA303", size = 2) +
  geom_text(data = filter(df, Year == last(Year)),
            aes(label = paste0(format(Year, "%Y"), "\n", round(Value, 1), "bn")),
            hjust = -0.3, size = 3, fontface = "bold") +
  coord_cartesian(clip = "off")
```

```{r}
# Global forest loss
# Source: Global Forest Watch
# URL: https://www.globalforestwatch.org/dashboards/global/

df <- read_csv("data/treecover_loss_in_primary_forests_2001_tropics_only__ha.csv") %>% 
  group_by(umd_tree_cover_loss__year) %>% 
  summarise(Value = sum(umd_tree_cover_loss__ha)) %>% 
  rename(Year = umd_tree_cover_loss__year) %>% 
  mutate(Year = ymd(Year, truncated = 2L),
         Value = Value / 1000000) # Million hectares

ggplot(df, aes(x = Year, y = Value)) +
  geom_col(fill = "#3EA303") +
  scale_x_date(expand = c(0.005, 0.005),
               breaks = seq.Date(as.Date("2001-01-01"), as.Date("2022-01-01"), by = "5 years"),
               date_labels = "%Y") + 
  scale_y_continuous(expand = c(0.005, 0.005), 
                     limits = c(0, 6.5),
                     position = "right") +
  labs(x = NULL, y = "Million hectares",
       title = "Global forest loss",
       subtitle = "Annual primary forest loss",
       caption = "Source: Global Forest Watch") +
  theme_minimal(base_size = 12) +
  theme(plot.margin = unit(rep(1.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(colour = "#000000"),
        plot.title.position = "plot",
        plot.title = element_markdown(face = "bold", size = 18),
        plot.subtitle = element_markdown(margin = margin(b = 25)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10), size = 12),
        axis.title.y.right = element_text(size = 8, angle = 0, vjust = 1, margin = margin(l = -60)))
```

```{r}
# Methane emissions
# Source: NOAA
# URL: https://gml.noaa.gov/ccgg/trends_ch4/

df <- read_csv("https://gml.noaa.gov/webdata/ccgg/trends/ch4/ch4_annmean_gl.csv",
               skip = 43) %>% 
  select(Year = year, Value = mean) %>% 
  mutate(Year = ymd(Year, truncated = 2L))

ggplot(df, aes(x = Year, y = Value, group = 1)) +
  geom_area(fill = "#CBFFA9") +
  geom_line(linewidth = 1, colour = "#3EA303") +
  scale_x_date(expand = c(0.005, 0.005),
               breaks = seq.Date(as.Date("1984-01-01"), as.Date("2022-01-01"), by = "5 years"),
               date_labels = "%Y") + 
  scale_y_continuous(expand = c(0.005, 0.005), 
                     limits = c(1600, 2030),
                     labels = comma) +
  labs(x = NULL, y = NULL,
       title = "Methane (CH<sub>4</sub>) emissions",
       subtitle = "Annual global mean methane levels in air",
       caption = "Source: NOAA") +
  theme_minimal(base_size = 12) +
  theme(plot.margin = unit(rep(1.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        axis.line.x = element_line(colour = "#000000"),
        plot.title.position = "plot",
        plot.title = element_markdown(face = "bold", size = 18),
        plot.subtitle = element_text(margin = margin(b = 25)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10), size = 12)) + 
  annotate("text", x = as.Date("1986-07-01"), y = 2020, label = "Parts per billion", size = 3) +
  geom_point(data = filter(df, Year == last(Year)),
             aes(x = Year, y = Value), 
             fill = "#CBFFA9", colour = "#3EA303", size = 2) +
  geom_text(data = filter(df, Year == last(Year)),
            aes(label = paste0(format(Year, "%Y"), "\n", format(round(Value, 0), big.mark = ",", scientific = FALSE)
)),
            hjust = -0.3, size = 3, fontface = "bold") +
  coord_cartesian(clip = "off")
```

```{r}
# Global average temperature change
# Source: Copernicus
# URL: https://climate.copernicus.eu/copernicus-october-2023-exceptional-temperature-anomalies-2023-virtually-certain-be-warmest-year

df <- read_csv("https://climate.copernicus.eu/sites/default/files/custom-uploads/era5_global_sfc_temp_monthly_anomalies_october_1940-2023%20(1).csv", skip = 6) %>% 
  select(Year = year, Value = `2t_ano`) %>% 
  mutate(Year = as.Date(paste(Year, 10, 1, sep = "-")), # October 
         Status = ifelse(Value < 0, "Below", "Above"))

ggplot(df, aes(x = Year, y = Value, fill = Status)) +
  geom_col(show.legend = FALSE) +
  geom_hline(yintercept = 0, linewidth = 1, colour = "#000000") +
  scale_fill_manual(values = c("Above" = "#D43A8B", "Below" = "#3EA303")) +
  scale_x_date(expand = c(0.005, 0.005),
               breaks = seq.Date(as.Date("1940-01-01"), as.Date("2023-10-01"), by = "10 years"),
               date_labels = "%Y") +
  scale_y_continuous(expand = c(0.005, 0.005), 
                     limits = c(-1.2, 1),
                     breaks = c(-1.2,-1,-0.8,-0.6,-0.4,-0.2,0,0.2,0.4,0.6,0.8,1),
                     labels = c(expression(-1.2~degree*C),
                                expression(-1~degree*C),
                                expression(-0.8~degree*C),
                                expression(-0.6~degree*C),
                                expression(-0.4~degree*C),
                                expression(-0.2~degree*C),
                                expression(0~degree*C),
                                expression(0.2~degree*C),
                                expression(0.4~degree*C),
                                expression(0.6~degree*C),
                                expression(0.8~degree*C),
                                expression(1.~degree*C)
                                )) +
  labs(x = NULL, y = NULL,
       title = "Global average temperature change - October",
       subtitle = "Average global surface temperature anomalies relative to a 1991-2020 baseline",
       caption = "Source: Copernicus") +
  theme_minimal(base_size = 12) +
  theme(plot.margin = unit(rep(1.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(face = "bold", size = 18),
        plot.subtitle = element_text(margin = margin(b = 25)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10), size = 12)) +
  geom_text(data = filter(df, Year == last(Year)),
            aes(label = paste0(format(Year, "%b %Y"), "\n+", round(Value, 2), "°C")),
            hjust = -0.3, size = 3, fontface = "bold") +
  coord_cartesian(clip = "off")
```

```{r}
# Rising sea levels
# Source: NOAA
# URL: https://www.star.nesdis.noaa.gov/socd/lsa/SeaLevelRise/LSA_SLR_timeseries_global.php
df <- read_csv("https://www.star.nesdis.noaa.gov/socd/lsa/SeaLevelRise/slr/slr_sla_gbl_keep_txj1j2_90.csv", skip = 5) %>% 
  mutate(Date = as.Date(date_decimal(year, tz = "UTC"))) %>% 
  select(-year) %>% 
  pivot_longer(-Date, names_to = "System", values_to = "Value") %>% 
  mutate(System = fct_relevel(System, "TOPEX/Poseidon", "Jason-1", "Jason-2", "Jason-3"))

ggplot(na.omit(df), aes(x = Date, y = Value, group = System, colour = System)) +
  geom_hline(yintercept = 0, linewidth = 1, colour = "#000000") +
  geom_line(key_glyph = "timeseries") +
  scale_colour_manual(values = c("TOPEX/Poseidon" = "#8CDC62",
                                 "Jason-1" = "#53A62A",
                                 "Jason-2" = "#2F700A",
                                 "Jason-3" = "#173D00")) +
  scale_x_date(expand = c(0.005, 0.005),
               breaks = seq.Date(as.Date("1995-01-01"), as.Date("2020-01-01"), by = "5 years"),
               date_labels = "%Y") + 
  scale_y_continuous(expand = c(0.005, 0.005), 
                     limits = c(-50, 115),
                     position = "right") +
  labs(x = NULL, y = "mm",
       title = "Rising sea levels",
       subtitle = "Change in global mean sea level from 1 January 2000",
       caption = "Source: NOAA",
       colour = "Monitoring system") +
  theme_minimal(base_size = 12) +
  theme(plot.margin = unit(rep(1.5, 4), "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(face = "bold", size = 18),
        plot.subtitle = element_text(margin = margin(b = 25)),
        plot.caption = element_text(colour = "grey60", margin = margin(t = 20, b = -10), size = 12),
        axis.title.y.right = element_text(size = 8, angle = 0, vjust = 1, margin = margin(l = -15)),
        legend.position = "top",
        legend.title = element_text(size = 10, face = "bold", colour = "#757575"),
        legend.text = element_text(size = 10, colour = "#757575"))
```

